version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  one:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

  two:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: rake?
          command: rake

workflows:
  version: 2.1
  one_and_two:
    jobs:
      - one
      - two
